from typing import Dict
import pandas as pd

def init_metrics(wind_price, solar_price, battery_1h_price, battery_2h_price, battery_4h_price, battery_6h_price, battery_8h_price, battery_12h_price, missing_energy_price) -> Dict[str, float]:
    metrics = {
        "produced_total": 0.0,
        "hours_met": 0,
        "excess_wind": 0.0,
        "excess_solar": 0.0,
        "redundant_wind": 0.0,
        "redundant_solar": 0.0,
        "excess_energy": 0.0,
        "missing_energy": 0.0,
        "wind_in_baseload": 0.0,
        "solar_in_baseload": 0.0,
        "charged_wind": 0.0,
        "charged_solar": 0.0,
        "discharged": 0.0,
        "cycle_loss": 0.0,
        "wind_price": wind_price,
        "solar_price": solar_price,
        "battery_1h_price": battery_1h_price,
        "battery_2h_price": battery_2h_price,
        "battery_4h_price": battery_4h_price,
        "battery_6h_price": battery_6h_price,
        "battery_8h_price": battery_8h_price,
        "battery_12h_price": battery_12h_price,
        "missing_energy_price": missing_energy_price,
    }
    return metrics

def compile_result(
    year: int,
    wind_cap: float,
    solar_cap: float,
    baseload: float,
    hours: int,
    battery_1h_mw: float,
    battery_2h_mw: float,
    battery_4h_mw: float,
    battery_6h_mw: float,
    battery_8h_mw: float,
    battery_12h_mw: float,
    wind_baseload: float,
    solar_baseload: float,
    wind_total: float,
    solar_total: float,
    vwap_missing: float,
    vwap_excess: float,
    vwap_wind: float,
    vwap_solar: float,
    m: Dict
) -> Dict:
    expected_baseload = baseload * hours
    return {
        "Simulation id": "",
        "year": year,
        "BL 1 - Fixed Missing EUR/MWh": "",
        "BL 2 - VWAP Missing EUR/MWh": "",
        "Break-even 1 - Fixed Missing, EUR/MWh": "",
        "Break-even 2 - VWAP Missing, EUR/MWh": "",
        "Break-even 3 - Fixed Excess, EUR/MWh": "",
        "Overproduction share, %": "",
        "Annual avg spot, EUR/MWh": "",
        "Res share in BL, %": round((m["produced_total"] / expected_baseload) * 100) if expected_baseload > 0 and pd.notna(
            m["produced_total"]) else 0.0,
        "Nr of green BL hours, h": m["hours_met"],
        "Nr of hours, h": hours,
        "Wind cap price, EUR/MWh": round(vwap_wind),
        "PV cap price, EUR/MWh": round(vwap_solar),
        "Missing energy VWAP, EUR/MWh": round(vwap_missing),
        "Excess energy VWAP, EUR/MWh": round(vwap_excess),
        "Baseload, MWh": expected_baseload,
        "Missing energy, MWh": round(0 if pd.isna(m["missing_energy"]) else m["missing_energy"]),
        "Cycle loss, MWh": round(m["cycle_loss_total"]),
        "Wind prod, MWh": round(wind_total),
        "Solar prod, MWh": round(solar_total),
        "Wind in BL, MWh": round(wind_baseload),
        "Solar in BL, MWh": round(solar_baseload),
        "Excess wind, MWh": round(m["excess_wind"]),
        "Excess solar, MWh": round(m["excess_solar"]),
        #"Redundant wind, MWh": round(m["redundant_wind"]),"
        #"Redundant solar, MWh": round(m["redundant_solar"]),
        "BESS 1h avg cycles": "",
        "BESS 1h zero hours ratio, %": "",
        "BESS 2h avg cycles": "",
        "BESS 2h zero hours ratio, %": "",
        "BESS 4h avg cycles": "",
        "BESS 4h zero hours ratio, %": "",
        "BESS 6h avg cycles": "",
        "BESS 6h zero hours ratio, %": "",
        "BESS 8h avg cycles": "",
        "BESS 8h zero hours ratio, %": "",
        "BESS 12h avg cycles": "",
        "BESS 12h zero hours ratio, %": "",

        "wind_capacity": round(wind_cap),
        "solar_capacity": round(solar_cap),
        "BESS_1h_CHARGE_MW": battery_1h_mw,
        "BESS_2h_CHARGE_MW": battery_2h_mw,
        "BESS_4h_CHARGE_MW": battery_4h_mw,
        "BESS_6h_CHARGE_MW": battery_6h_mw,
        "BESS_8h_CHARGE_MW": battery_8h_mw,
        "BESS_12h_CHARGE_MW": battery_12h_mw,
        "Baseload, MW": baseload,
        "Wind PaP price, EUR/MWh": m["wind_price"],
        "PV PaP price, EUR/MWh": m["solar_price"],
        "BESS 1h annual payment, EUR/MWh": m["battery_1h_price"],
        "BESS 2h annual payment, EUR/MWh": m["battery_2h_price"],
        "BESS 4h annual payment, EUR/MWh": m["battery_4h_price"],
        "BESS 6h annual payment, EUR/MWh": m["battery_6h_price"],
        "BESS 8h annual payment, EUR/MWh": m["battery_8h_price"],
        "BESS 12h annual payment, EUR/MWh": m["battery_12h_price"],
        "Missing energy price, EUR/MWh": m["missing_energy_price"],
    }